export const categories = [
  {
    name: "Architecture",
    code: "ARCH",
    subLabels: ["ARCH - Architecture", "LGHT - Lighting"],
  },
  {
    name: "Engineering",
    code: "ENGR",
    subLabels: [
      "BMED - Biomedical Engineering",
      "CHME - Chemical Engineering",
      "CIVL - Civil Engineering",
      "ECSE - Electrical, Computer, and Systems Engineering",
      "ENGR - General Engineering",
      "ENVE - Environmental Engineering",
      "ESCI - Engineering Science",
      "ISYE - Industrial and Systems Engineering",
      "MANE - Mechanical, Aerospace, and Nuclear Engineering",
      "MTLE - Materials Science and Engineering",
    ],
  },
  {
    name: "Information Technology and Web Science",
    code: "ITWS",
    subLabels: ["ITWS - Information Technology and Web Science"],
  },
  {
    name: "Humanities, Arts, and Social Sciences",
    code: "HASS",
    subLabels: [
      "ARTS - Arts",
      "COGS - Cognitive Science",
      "COMM - Communication",
      "ECON - Economics",
      "GSAS - Games and Simulation Arts and Sciences",
      "IHSS - Interdisciplinary Humanities and Social Sciences",
      "INQR - HASS Inquiry",
      "LANG - Foreign Languages",
      "LITR - Literature",
      "PHIL - Philosophy",
      "PSYC - Psychology",
      "STSO - Science, Technology, and Society",
      "WRIT - Writing",
    ],
  },
  {
    name: "Uncategorized",
    code: "ILEA",
    subLabels: ["ILEA - Independent Learning Exper"],
  },
  {
    name: "Interdisciplinary & Other",
    code: "INTER",
    subLabels: [
      "ADMN - Administrative Courses",
      "USAF - Aerospace Studies (Air Force ROTC)",
      "USAR - Military Science (Army ROTC)",
      "USNA - Naval Science (Navy ROTC)",
    ],
  },
  {
    name: "Management",
    code: "MGMT",
    subLabels: ["BUSN - Business (H)", "MGMT - Management"],
  },
  {
    name: "Science",
    code: "SCI",
    subLabels: [
      "ASTR - Astronomy",
      "BCBP - Biochemistry and Biophysics",
      "BIOL - Biology",
      "CHEM - Chemistry",
      "CSCI - Computer Science",
      "ERTH - Earth and Environmental Science",
      "ISCI - Interdisciplinary Science",
      "MATH - Mathematics",
      "MATP - Mathematical Programming, Probability, and Statistics",
      "PHYS - Physics",
    ],
  },
]; 